#!/usr/bin/env python3
"""Generate docs/library-audit.md — a read-only classification of every library
item (skills, commands, rules, prompts, templates) with a proposed migration
target and action. Non-destructive: it only reads the repo and writes the audit.

Run: python3 scripts/library_audit.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "library-audit.md"

CATEGORY_KEYWORDS = {
    "presentation": ["slide", "deck", "presentation", "keynote", "ppt", "pitch"],
    "data-visualization": ["chart", "graph", "kpi", "visualization", "dashboard"],
    "design": ["design", "typograph", "color", "spacing", "layout", "brand", "visual", "css", "figma"],
    "accessibility": ["accessib", "a11y", "aria", "wcag", "contrast"],
    "research": ["research", "interview", "persona", "survey", "discovery", "jobs-to-be-done", "jtbd"],
    "strategy": ["strategy", "positioning", "roadmap", "okr", "prioriti", "market", "competitive"],
    "product": ["product", "prd", "epic", "user story", "press release", "backlog", "sprint"],
    "frontend": ["frontend", "react", "component", "tailwind", "animation", "motion"],
    "development": ["debug", "refactor", "compile", "lint", "git", "ci"],
    "writing": ["copywrit", "writing", "microcopy", "tone", "editorial", "changelog", "seo"],
    "ux": ["ux", "journey", "usability", "flow"],
    "automation": ["automation", "pipeline", "zapier"],
    "agent-tools": ["agent", "mcp", "cursor", "claude", "codex", "plugin", "skill", "prompt"],
    "documentation": ["documentation", "readme", "docs"],
    "productivity": ["plan", "review", "ship", "handoff", "retro"],
}

WORKFLOW_HINTS = ["end-to-end", "multi-step", "phase", "step 1", "workflow", "orchestrat", "sequence"]
GLOBAL_RULES = {"tight-diffs", "verify-before-done"}


def fm(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out = {}
    for line in text[text.find("\n", 3) + 1 : end + 1].splitlines():
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if m and m.group(2).strip():
            out[m.group(1)] = m.group(2).strip().strip("\"'")
    return out


def category(text: str, name: str) -> str:
    hay = f"{name} {text}".lower()
    best, score = "", 0
    for cat, kws in CATEGORY_KEYWORDS.items():
        n = sum(hay.count(k) for k in kws)
        if n > score:
            best, score = cat, n
    return best or "—"


def desc(text: str, meta: dict) -> str:
    d = meta.get("description", "")
    if not d:
        for line in text.splitlines():
            s = line.strip()
            if s and not s.startswith(("#", "---", "-", "|", "```", "type:")):
                d = s
                break
    return re.sub(r"\s+", " ", d)[:90].replace("|", "\\|")


def read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def skill_names(base: Path) -> set[str]:
    return {p.parent.name for p in base.glob("*/SKILL.md")} if base.is_dir() else set()


def cmd_target(text: str) -> str:
    m = re.search(r"skills/([a-z0-9-]+)/", text)
    return m.group(1) if m else ""


def main() -> int:
    root_skills = sorted(skill_names(ROOT / "skills"))
    prompt_cmds = sorted(p.stem for p in (ROOT / "prompts" / "commands").glob("*.md")) if (ROOT / "prompts" / "commands").is_dir() else []
    dup = sorted(set(root_skills) & set(prompt_cmds))

    L: list[str] = []
    L.append("# Library audit")
    L.append("")
    L.append("_Auto-generated by `scripts/library_audit.py` — read-only classification of every "
             "item with a proposed target + action. Nothing is moved by this script._")
    L.append("")
    L.append("## Summary")
    L.append("")
    L.append("| Area | Count |")
    L.append("| --- | --- |")
    L.append(f"| Root skills (`skills/`) | {len(root_skills)} |")
    L.append(f"| Root commands (`commands/`) | {len(list((ROOT/'commands').glob('*.md')))} |")
    L.append(f"| Root rules (`rules/`) | {len(list((ROOT/'rules').glob('*.mdc')))} |")
    L.append(f"| Prompt commands (`prompts/commands/`) | {len(prompt_cmds)} |")
    L.append(f"| Prompt templates (`prompts/prompts/`) | {len(list((ROOT/'prompts'/'prompts').rglob('*.md')))} |")
    L.append(f"| Prompt-kit skills (`prompts/skills/`) | {len(skill_names(ROOT/'prompts'/'skills'))} |")
    L.append("")

    # Duplicates
    L.append("## Duplicate / overlap hot-spots")
    L.append("")
    L.append("Items that exist as **both** a root skill and a prompt command — consolidate to "
             "one canonical skill; keep a thin prompt that invokes it.")
    L.append("")
    L.append("| Name | root skill | prompt command | Action |")
    L.append("| --- | --- | --- | --- |")
    for n in dup:
        L.append(f"| `{n}` | ✓ | ✓ | DEDUPE → canonical `skills/{n}`; retire `prompts/commands/{n}.md` |")
    if not dup:
        L.append("| — | | | none |")
    L.append("")

    # Root skills
    L.append("## Root skills → `skills/`")
    L.append("")
    L.append("| Skill | Category | Proposed action | Description |")
    L.append("| --- | --- | --- | --- |")
    for n in root_skills:
        text = read(ROOT / "skills" / n / "SKILL.md")
        meta = fm(text)
        cat = category(text, n)
        low = text.lower()
        if n in dup:
            action = "DEDUPE (see above)"
        elif any(h in low for h in WORKFLOW_HINTS):
            action = "REVIEW → candidate workflow"
        else:
            action = "KEEP · normalize to SKILL schema"
        L.append(f"| `{n}` | {cat} | {action} | {desc(text, meta)} |")
    L.append("")

    # Root commands
    L.append("## Root commands → invocation layer")
    L.append("")
    L.append("Slash-command shims. Keep as the invocation layer; point each at its skill/prompt.")
    L.append("")
    L.append("| Command | Routes to | Action |")
    L.append("| --- | --- | --- |")
    for p in sorted((ROOT / "commands").glob("*.md")):
        tgt = cmd_target(read(p))
        L.append(f"| `/{p.stem}` | {('skills/'+tgt if tgt else '—')} | keep as command shim |")
    L.append("")

    # Rules
    L.append("## Root rules → global vs scoped")
    L.append("")
    L.append("| Rule | Proposed action |")
    L.append("| --- | --- |")
    for p in sorted((ROOT / "rules").glob("*.mdc")):
        n = p.stem
        act = "→ GLOBAL (fold into AGENTS.md)" if n in GLOBAL_RULES else "keep as scoped rule (pairs with skill)"
        L.append(f"| `{n}` | {act} |")
    L.append("")

    # Prompt commands
    L.append("## Prompt commands → `prompts/<category>/`")
    L.append("")
    L.append("| Prompt | Category | Action |")
    L.append("| --- | --- | --- |")
    for n in prompt_cmds:
        text = read(ROOT / "prompts" / "commands" / f"{n}.md")
        cat = category(text, n)
        action = f"DEDUPE → merge into `skills/{n}`" if n in dup else f"KEEP prompt → `prompts/{cat}/`"
        L.append(f"| `{n}` | {cat} | {action} |")
    L.append("")

    # Templates
    tdir = ROOT / "prompts" / "prompts"
    if tdir.is_dir():
        L.append("## Prompt templates → `templates/`")
        L.append("")
        L.append("| Template | Proposed target |")
        L.append("| --- | --- |")
        for p in sorted(tdir.rglob("*.md")):
            rel = p.relative_to(tdir)
            cat = category(read(p), p.stem)
            L.append(f"| `{rel}` | `templates/{cat}/{p.name}` |")
        L.append("")

    # Migration batches
    L.append("## Proposed migration batches (each a reviewable PR)")
    L.append("")
    L.append("1. **Global docs** — done (`AGENTS.md`, `DESIGN.md`, `CLAUDE.md`, `LIBRARY.md`).")
    L.append("2. **Schemas + tiers** — done (`references/schemas/`, `workflows/`, `references/`).")
    L.append("3. **De-dupe the PM overlaps** — consolidate the duplicate table above into canonical "
             "skills; replace each `prompts/commands/*` duplicate with a thin invoking prompt.")
    L.append("4. **Fold global rules** — move `tight-diffs` / `verify-before-done` guidance into `AGENTS.md`.")
    L.append("5. **Relocate templates** — `prompts/prompts/*` → `templates/<category>/`.")
    L.append("6. **Normalize skills** — bring each `skills/*/SKILL.md` up to the schema in small batches; "
             "replace restated design rules with `See /DESIGN.md`.")
    L.append("7. **Promote workflows** — move multi-phase skills (flagged above) into `workflows/`.")
    L.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(root_skills)} skills, {len(prompt_cmds)} prompt commands, {len(dup)} duplicates.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
